global_defs {
    router_id SIMANIS_STANDBY
    script_user root
    enable_script_security
}

vrrp_script chk_simanis {
    script "/usr/local/sbin/check-simanis-ha"
    interval 3
    timeout 3
    fall 2
    rise 2
}

vrrp_instance VI_SIMANIS {
    state BACKUP
    interface enp0s31f6
    virtual_router_id 51
    priority 100
    advert_int 1
    nopreempt

    authentication {
        auth_type PASS
        auth_pass SimaHA26
    }

    unicast_src_ip 192.168.0.10
    unicast_peer {
        192.168.0.11
    }

    virtual_ipaddress {
        192.168.0.12/24 dev enp0s31f6
    }

    track_script {
        chk_simanis
    }

    notify_master "/usr/local/sbin/simanis-ha-master"
    notify_backup "/usr/local/sbin/simanis-ha-backup"
}
